#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and Hi before the last
counter=1

# Using a while loop to display "Best School" 10 times with a special case
while [ $counter -le 10 ]; do
  if [ $counter -eq 9 ]; then
    # Special case for the 9th iteration
    echo -e "Best School\nHi"
  else
    echo "Best School"
  fi

  # Increment the counter
  ((counter++))
done
