#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but bad luck at 4th round and good luck at 8th round
counter=1

# Using a while loop to display "Best School" 10 times with a special case
while [ $counter -le 10 ]; do
  if [ $counter -eq 4 ]; then
    # Special case for the 4th iteration
    echo "bad luck"
  elif [ $counter -eq 8 ]; then
    # Special case for the 8th iteration
    echo "good luck"
  else
    echo "Best School"
  fi

  # Increment the counter
  ((counter++))
done
