#!/usr/bin/env bash
# This script is displaying time

hour=0
minute=1
while [ $hour -le 12 ]; do
  echo "Hour: $hour"
  minute=1
  while [ $minute -lt 60 ]; do
    echo "$minute"
    ((minute++))
  done
  ((hour++))
done
